@props([
    'series' => [],
    'categories' => [],
    'title' => null,
    'subtitle' => null,
    'height' => '320px',
    'width' => '100%',
    'legend' => true,
    'toolbar' => false,
    'loading' => false,
    'emptyMessage' => 'No data available',
    'colors' => null,
    'palette' => ['primary', 'secondary', 'accent', 'info', 'success', 'warning', 'error'],
    'valueFormat' => 'number',
    'tooltipFormat' => null,
    'options' => [],
    'module' => null,
    'drilldownUrl' => null,
    'drilldownParams' => [],
    'aria' => true,
    'markers' => [],
    'zoom' => false,
    'zoomMode' => 'inside',
    'renderer' => 'svg',
    'action' => null,
    'showValues' => false,
    'centerValue' => null,
    'centerLabel' => null,
    'dataTable' => true,
    'dataTableLabel' => 'Voir les données',
])

@include('daisy::partials.charts.renderer', ['preset' => 'donut'])
