<?php

declare(strict_types=1);

$root = dirname(__DIR__);
$componentsPath = $root.'/resources/views/components';
$templatesPath = $root.'/resources/views/templates';
$referencesPath = $root.'/resources/boost/skills/daisy-kit-component-reuse/references';

$componentTemplateMirrorCount = countBladeFiles($componentsPath.'/templates');
$components = collectComponents($componentsPath);
$templates = collectTemplates($templatesPath);

$payload = [
    'generated_at' => date(DATE_ATOM),
    'package' => 'art35rennes/laravel-daisy-kit',
    'blade_namespace' => 'daisy::',
    'summary' => [
        'component_count' => count($components),
        'template_count' => count($templates),
        'excluded_component_template_mirrors' => $componentTemplateMirrorCount,
    ],
    'components' => $components,
    'templates' => $templates,
];

ensureDirectory($referencesPath);

file_put_contents(
    $referencesPath.'/components.json',
    json_encode($payload, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES).PHP_EOL
);

file_put_contents(
    $referencesPath.'/component-catalog.md',
    renderCatalogMarkdown($payload)
);

fwrite(
    STDOUT,
    sprintf(
        "Generated AI catalog with %d components and %d templates.\n",
        count($components),
        count($templates),
    )
);

function collectComponents(string $componentsPath): array
{
    $entries = [];

    foreach (bladeFiles($componentsPath) as $file) {
        $relative = relativeBladePath($componentsPath, $file);

        // Anonymous component templates are cataloged once through resources/views/templates.
        if (str_starts_with($relative, 'templates/')) {
            continue;
        }

        $logicalName = str_replace('.blade.php', '', $relative);
        $segments = explode('/', $logicalName);

        $entries[] = [
            'alias' => 'x-daisy::'.str_replace('/', '.', $logicalName),
            'group' => count($segments) > 1 ? implode('.', array_slice($segments, 0, -1)) : 'root',
            'name' => end($segments),
            'relative_path' => 'resources/views/components/'.$relative,
            'props' => extractProps($file),
        ];
    }

    usort($entries, static fn (array $left, array $right): int => strcmp($left['alias'], $right['alias']));

    return $entries;
}

function collectTemplates(string $templatesPath): array
{
    $entries = [];

    foreach (bladeFiles($templatesPath) as $file) {
        $relative = relativeBladePath($templatesPath, $file);
        $logicalName = str_replace('.blade.php', '', $relative);
        $segments = explode('/', $logicalName);

        $entries[] = [
            'component_alias' => 'x-daisy::templates.'.str_replace('/', '.', $logicalName),
            'view_alias' => 'daisy::templates.'.str_replace('/', '.', $logicalName),
            'group' => count($segments) > 1 ? implode('.', array_slice($segments, 0, -1)) : 'root',
            'name' => end($segments),
            'relative_path' => 'resources/views/templates/'.$relative,
            'props' => extractProps($file),
        ];
    }

    usort($entries, static fn (array $left, array $right): int => strcmp($left['component_alias'], $right['component_alias']));

    return $entries;
}

function extractProps(string $file): array
{
    $content = file_get_contents($file);

    if ($content === false || ! preg_match('/@props\s*\(\s*\[(.*?)\]\s*\)/s', $content, $matches)) {
        return [];
    }

    preg_match_all('/[\'"]([A-Za-z0-9_-]+)[\'"]\s*=>/m', $matches[1], $propMatches);

    $props = [];

    foreach ($propMatches[1] as $prop) {
        if (! in_array($prop, $props, true)) {
            $props[] = $prop;
        }
    }

    return $props;
}

function renderCatalogMarkdown(array $payload): string
{
    $lines = [];
    $generatedAt = $payload['generated_at'];
    $summary = $payload['summary'];

    $lines[] = '# Daisy Kit Component Catalog';
    $lines[] = '';
    $lines[] = 'Generated by `composer ai:catalog`. Do not edit by hand.';
    $lines[] = '';
    $lines[] = '- Package: `art35rennes/laravel-daisy-kit`';
    $lines[] = '- Blade namespace: `daisy::`';
    $lines[] = '- Component count: `'.$summary['component_count'].'`';
    $lines[] = '- Template count: `'.$summary['template_count'].'`';
    $lines[] = '- Excluded template mirrors from `resources/views/components/templates`: `'.$summary['excluded_component_template_mirrors'].'`';
    $lines[] = '- Generated at: `'.$generatedAt.'`';
    $lines[] = '';
    $lines[] = '## Reuse Order';
    $lines[] = '';
    $lines[] = '1. Reuse an existing `x-daisy::layout.*`, `x-daisy::ui.*`, or `x-daisy::templates.*` alias.';
    $lines[] = '2. Compose multiple package components before inventing a new host-side Blade component.';
    $lines[] = '3. Prefer published overrides under `resources/views/vendor/daisy/...` for light visual changes.';
    $lines[] = '4. Create a new host component or layout only when the package surface is clearly insufficient.';
    $lines[] = '';
    $lines[] = '## Components';
    $lines[] = '';

    foreach (groupEntries($payload['components'], 'group') as $group => $entries) {
        $lines[] = '### `'.$group.'`';
        $lines[] = '';

        foreach ($entries as $entry) {
            $lines[] = '- `'.$entry['alias'].'`';
            $lines[] = '  Path: `'.$entry['relative_path'].'`';
            $lines[] = '  Props: '.formatProps($entry['props']);
        }

        $lines[] = '';
    }

    $lines[] = '## Templates';
    $lines[] = '';

    foreach (groupEntries($payload['templates'], 'group') as $group => $entries) {
        $lines[] = '### `'.$group.'`';
        $lines[] = '';

        foreach ($entries as $entry) {
            $lines[] = '- `'.$entry['component_alias'].'`';
            $lines[] = '  View: `'.$entry['view_alias'].'`';
            $lines[] = '  Path: `'.$entry['relative_path'].'`';
            $lines[] = '  Props: '.formatProps($entry['props']);
        }

        $lines[] = '';
    }

    return implode(PHP_EOL, $lines);
}

function formatProps(array $props): string
{
    if ($props === []) {
        return 'none declared';
    }

    return '`'.implode('`, `', $props).'`';
}

function groupEntries(array $entries, string $key): array
{
    $grouped = [];

    foreach ($entries as $entry) {
        $grouped[$entry[$key]][] = $entry;
    }

    ksort($grouped);

    return $grouped;
}

function bladeFiles(string $path): array
{
    if (! is_dir($path)) {
        return [];
    }

    $files = [];
    $iterator = new RecursiveIteratorIterator(
        new RecursiveDirectoryIterator($path, FilesystemIterator::SKIP_DOTS)
    );

    foreach ($iterator as $file) {
        if (! $file->isFile()) {
            continue;
        }

        $pathname = $file->getPathname();

        if (! str_ends_with($pathname, '.blade.php')) {
            continue;
        }

        $files[] = $pathname;
    }

    sort($files);

    return $files;
}

function countBladeFiles(string $path): int
{
    return count(bladeFiles($path));
}

function relativeBladePath(string $basePath, string $file): string
{
    return str_replace(
        ['\\', rtrim($basePath, DIRECTORY_SEPARATOR).DIRECTORY_SEPARATOR],
        ['/', ''],
        $file
    );
}

function ensureDirectory(string $path): void
{
    if (is_dir($path)) {
        return;
    }

    mkdir($path, 0755, true);
}
